"""
Tulsa City Spider Factory

⚠️ AI-GENERATED CODE - NOT YET REVIEWED BY A HUMAN ⚠️

This file was generated by Claude (Anthropic) as part of the initial
city-scrapers-tulsa repository setup. The selectors and agency_ids are
placeholders that need to be updated based on actual website analysis.

Dynamically creates spider classes for Tulsa city agencies that share
a common calendar/meeting system. Based on the Wichita spider factory
pattern from city-scrapers-wichita.

To add a new agency:
1. Find the agency_id used in the Tulsa website URLs
2. Add a new configuration dict to spider_configs
3. Run `scrapy list` to verify the spider was created
4. Test with `scrapy crawl tulok_<agency_name>`
"""

from city_scrapers.mixins.tulsa_city import TulsaCityMixin

# Configuration for each spider
# Based on agencies from AGENCIES.md
# NOTE: agency_id values are PLACEHOLDERS - need to be updated based on actual website
spider_configs = [
    # City Council and Core Agencies
    {
        "class_name": "TulokCityCouncilSpider",
        "name": "tulok_city_council",
        "agency": "Tulsa City Council",
        "agency_id": "1642",
    },
    {
        "class_name": "TulokCountyCommissionersSpider",
        "name": "tulok_county_commissioners",
        "agency": "Tulsa Board of County Commissioners",
        "agency_id": "1846",
    },
    # Commissions
    {
        "class_name": "TulokArtsCommissionSpider",
        "name": "tulok_arts_commission",
        "agency": "Arts Commission of City of Tulsa",
        "agency_id": "1645",
    },
    {
        "class_name": "TulokAsianAffairsSpider",
        "name": "tulok_asian_affairs",
        "agency": "Asian Affairs Commission",
        "agency_id": "1665",
    },
    {
        "class_name": "TulokAuditCommitteeSpider",
        "name": "tulok_audit_committee",
        "agency": "Audit Committee of the City of Tulsa",
        "agency_id": "1666",
    },
    {
        "class_name": "TulokBeyondApologySpider",
        "name": "tulok_beyond_apology",
        "agency": "Beyond Apology Commission",
        "agency_id": "1667",
    },
    {
        "class_name": "TulokPortAuthoritySpider",
        "name": "tulok_port_authority",
        "agency": "City of Tulsa-Rogers County Port Authority",
        "agency_id": "1670",
    },
    {
        "class_name": "TulokEmsaSpider",
        "name": "tulok_emsa",
        "agency": "Emergency Medical Services Authority",
        "agency_id": "1737",
    },
    {
        "class_name": "TulokGilcreaseSpider",
        "name": "tulok_gilcrease",
        "agency": "Gilcrease Museum Board of Trustees",
        "agency_id": "1739",
    },
    {
        "class_name": "TulokAfricanAmericanSpider",
        "name": "tulok_african_american",
        "agency": "Greater Tulsa Area African-American Affairs Commission",
        "agency_id": "1740",
    },
    {
        "class_name": "TulokAnimalWelfareSpider",
        "name": "tulok_animal_welfare",
        "agency": "Tulsa Animal Welfare Commission",
        "agency_id": "1644",
    },
    {
        "class_name": "TulokBoaSpider",
        "name": "tulok_boa",
        "agency": "Tulsa Board of Adjustment",
        "agency_id": "1668",
    },
    {
        "class_name": "TulokAppealsSpider",
        "name": "tulok_appeals",
        "agency": "Tulsa Board of Appeals",
        "agency_id": "1669",
    },
    {
        "class_name": "TulokCivilServiceSpider",
        "name": "tulok_civil_service",
        "agency": "Tulsa Civil Service Commission",
        "agency_id": "1671",
    },
    {
        "class_name": "TulokCommunityDevSpider",
        "name": "tulok_community_dev",
        "agency": "Tulsa Community Development Committee",
        "agency_id": "1672",
    },
    {
        "class_name": "TulokDevAuthoritySpider",
        "name": "tulok_dev_authority",
        "agency": "Tulsa Development Authority",
        "agency_id": "1787",
    },
    {
        "class_name": "TulokElectionSpider",
        "name": "tulok_election",
        "agency": "Tulsa Election District Commission",
        "agency_id": "1736",
    },
    {
        "class_name": "TulokEthicsSpider",
        "name": "tulok_ethics",
        "agency": "Tulsa Ethics Advisory Committee",
        "agency_id": "1738",
    },
    {
        "class_name": "TulokParksRecSpider",
        "name": "tulok_parks_rec",
        "agency": "Tulsa Parks and Recreation Board",
        "agency_id": "1788",
    },
    {
        "class_name": "TulokPublicSchoolsSpider",
        "name": "tulok_public_schools",
        "agency": "Tulsa Public Schools Board of Education",
        "agency_id": "1583",
    },
    {
        "class_name": "TulokStadiumTrustSpider",
        "name": "tulok_stadium_trust",
        "agency": "Tulsa Stadium Trust",
        "agency_id": "1742",
    },
    {
        "class_name": "TulokWomensSpider",
        "name": "tulok_womens",
        "agency": "Tulsa Women's Commission",
        "agency_id": "1741",
    },
    {
        "class_name": "TulokUnionSchoolsSpider",
        "name": "tulok_union_schools",
        "agency": "Union Public Schools Board of Education",
        "agency_id": "1789",
    },
    {
        "class_name": "TulokCitySpider",
        "name": "tulok_city",
        "agency": "City of Tulsa",
        "agency_id": "1881",
    },
]


def create_spiders():
    """
    Dynamically create spider classes using the spider_configs list
    and register them in the global namespace.

    This approach is equivalent to declaring each spider class manually
    but is more maintainable when dealing with many similar spiders.

    Each spider inherits from TulsaCityMixin and gets the configuration
    values (name, agency, agency_id) as class attributes.
    """
    for config in spider_configs:
        # Get class name without modifying the original config dict
        class_name = config["class_name"]

        # Prevent duplicate class creation
        # (some Scrapy commands import this module multiple times)
        if class_name not in globals():
            # Build attributes dict without class_name
            attrs = {k: v for k, v in config.items() if k != "class_name"}

            # Dynamically create the spider class
            # type(name, bases, dict) creates a new class
            spider_class = type(
                class_name,           # Class name
                (TulsaCityMixin,),    # Base classes (tuple)
                attrs,                # Class attributes (dict)
            )

            # Register the class in the global namespace
            # This makes it discoverable by Scrapy
            globals()[class_name] = spider_class


# Call the function to create all spider classes
# This must be at module level (not inside an if __name__ == "__main__" block)
create_spiders()
